### ISSUE TITLE
[BUG] Not working as intended

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [ArnaudBarre/eslint-plugin-react-refresh#3] opened 2022-12-26 20:04 UTC
README suggests to do this:
```
{
  "plugins": ["react-refresh"],
  "rules": {
    "react-refresh/only-export-components": "warn"
  }
}
```

But the plugin is doing the wrong exports, infact i only got it working by doing:
```
{
  "plugins": ["only-export-components"],
  "rules": {
    "only-export-components/only-export-components": "warn"
  }
}
```

**Comment by ArnaudBarre** [comment] 2022-12-27 23:01
The plugin name is based on the npm package. I think something is wrong in your setup. Do you have a small reproduction?

**Comment by AndreaPontrandolfo** [comment] 2022-12-28 09:51
Sure, this is my usecase: https://github.com/AndreaPontrandolfo/sheriff/blob/master/configs/eslint.config.js#L536
I'm on the EslintFlatConfig.

**Comment by ArnaudBarre** [comment] 2022-12-28 12:44
Seems like you are using a namespace: https://eslint.org/blog/2022/08/new-config-system-part-2/#personalized-plugin-namespaces

The documentation is for the current configuration setup and I think it's fine for now because the flat config is still marked as experimental: https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new

Closing as work as intended

**Closed by ArnaudBarre** 2022-12-28 12:44 UTC
